export { Slider } from './slider/slider'
export { VideoPlayer } from './playVideo'
export { MainSlider } from './slider/slider-main'
export { MiniSlider } from './slider/slider-mini'
export { Difference } from './difference'
export { Form } from './forms'
